version: '3'

services:
  node:
    image: node:14.12.0-alpine3.10
    volumes:
      - ./:/app
    working_dir: /app
    command: "node dist/app.js"
    environment:
      - "HTTP_PORT=3000"
    ports:
      - 3000:3000
    restart: on-failure
